[package]
name = "wqbot"
version = "0.1.0"
description = "WQBot - Intelligent AI Butler"
authors = ["WQBot Team"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "app-all", "updater", "process-relaunch", "shell-open", "shell-sidecar", "window-all", "http-all", "process-command-api"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
